import '@/styles/globals.css'
import type { Metadata } from 'next'

import { Noto_Sans_JP, Roboto_Mono } from 'next/font/google'
import { twMerge } from 'tailwind-merge'
import { Providers } from './providers'

const NotoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-sans-jp',
})

const RobotoMono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  alternates: {},
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const originTrialToken = process.env.DC_ORIGIN_TRIAL_TOKEN
  if (!originTrialToken) {
    throw new Error('DC_ORIGIN_TRIAL_TOKEN is not set')
  }

  return (
    <html lang='ja' className={`${NotoSansJp.variable} ${RobotoMono.variable}`}>
      <head>
        <meta httpEquiv='origin-trial' content={originTrialToken} />
      </head>
      <body className={twMerge('min-h-screen bg-background font-noto antialiased')}>
        <Providers>
          <div className='relative flex h-screen flex-col'>{children}</div>
        </Providers>
      </body>
    </html>
  )
}
